HISTORICAL_DATE_COLUMN = "datetime"
HISTORICAL_ITEM_COLUMN = "unique_id"
HISTORICAL_TARGET_COLUMN = "value"

FREQUENCY = "D"

MIN_PRED_DATE = "2022-01-01"
MAX_PRED_DATE = "2023-06-30"
N_PRED_STEPS = 48
MIN_PRED_DATE_LIMIT = 1
MAX_PRED_DATE_LIMIT = 128
